[nix]
channel = "nixpkgs-unstable"

[phases.setup]
nixPkgs = [
  "python311",
  "poetry",
  "nodejs",
  "playwright",
  "glibc",
  "gcc",
  "make"
]

[phases.install]
cmds = [
  "poetry config virtualenvs.create false",
  "poetry install --no-interaction --no-ansi --no-dev"
]

[phases.build]
cmds = [
  "poetry run playwright install chromium",
  "poetry run playwright install-deps chromium"
]

[variables]
PYTHONUNBUFFERED = "1"
PORT = "8000"

