[nix]
channel = "nixpkgs-unstable"

[phases.setup]
nixPkgs = [
  "nodejs",
  "python3",
  "playwright",
  "glibc"
]

[phases.build]
cmds = [
  "npx playwright install chromium chromium-headless-shell"
] 