[nix]
channel = "nixpkgs-unstable"

[phases.setup]
nixPkgs = [
  "nodejs",
  "python3",
  "poetry",
  "playwright",
  "glibc",
  "gcc"
]

[phases.install]
cmds = [
  "poetry config virtualenvs.create false",
  "poetry install --no-interaction --no-ansi --no-dev"
]

[phases.build]
cmds = [
  "poetry run playwright install chromium chromium-headless-shell",
  "poetry run playwright install-deps chromium"
]

[variables]
PYTHONUNBUFFERED = "1" 